-- Blizzard MM2 v1.85.4 - Fling.lua QUICK BUTTON UPDATE
--
-- Apply these two exact changes to the "ORIGINAL MOVABLE ROLE BUTTONS"
-- section of the current Fling.lua. No fling/anti-fling logic changes.
--
-- The updated UI.lua signature is:
-- UI.CreateMovableCardButton(name, icon, labelText, startPosition, callback, accent)
--
-- Replace the sheriff/hero quick-button call with:
--
-- local FloatingFlingSheriffButton,
--     FloatingFlingSheriffHolder =
--     UI.CreateMovableCardButton(
--         "FloatingFlingSheriff",
--         "shield",
--         "FLING SHERIFF/HERO",
--         UDim2.new(0.78,-52,0.78,-42),
--         function()
--             FlingSheriffOrHero()
--         end,
--         "blue"
--     )
--
-- Replace the murderer quick-button call with:
--
-- local FloatingFlingMurdererButton,
--     FloatingFlingMurdererHolder =
--     UI.CreateMovableCardButton(
--         "FloatingFlingMurderer",
--         "wind",
--         "FLING MURDERER",
--         UDim2.new(0.89,-52,0.78,-42),
--         function()
--             FlingRole("Murderer","Murderer")
--         end,
--         "red"
--     )
--
-- Keep the existing Holder.Visible assignments and MM2.UI assignments.
